### PR TITLE
add get public address route

### PR DESCRIPTION
**Pull request by Pantani**
Example:

`http://localhost:8399/v1/address/714`

```
{
   "address" : "bnb1qxm48ndhmh7su0r7zgwmwkltuqgly57jruwqfk",
   "coin" : 714,
   "coin_name" : "BNB"
}
```

### CODE REVIEW

**Comment by vikmeup** [comment]
What is the purpose for this API?

**Comment by Pantani** [comment]
> What is the purpose for this API?

@onggunhao ask me for this API to show the address and balances of the main wallets inside the dashboard

**Comment by vikmeup** [comment]
Can we remove this PR code from master? As it’s not longer needed

**Comment by vikmeup** [comment]
@Pantani

**Pull request merged**
